# This is a basic workflow to help you get started with Actions

name: TF_Deploy_dev
on:
  push:
    branches: [ main,'dev','prod']
    paths: 
      - '**.tf'
      - '**.tfvars'
 
  pull_request:
    types: [ 'labeled','opened','synchronize','reopened']
    branches: [ 'main','dev','prod' ]
    paths: 
      - '**.tf'
      - '**.tfvars'


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      runapply:
        description: 'Enter yes or no if apply should be run'
        required: true
        default: 'No'
    
    #${{ github.event.inputs.runapply =='' }}
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  log-github-event-goodies:
    name: "LOG Everything on GitHub Event"
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: |
          echo "${{toJSON(github.event)}}"
          
  build:
    name: 'TF_prepare'
    runs-on: ubuntu-latest
    environment: dev

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    #====================================#
    # Checkout the repository to the GitHub Actions runner
    #====================================#
    - name: Checkout
      uses: actions/checkout@v2
