# This is a basic workflow to help you get started with Actions

name: install_app_dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Install Helm chart react_redux
        uses: hahow/install-helm-chart-action@v1
        with:
          gcloud_auth_key: ${{ secrets.G_INFO }}
          gcloud_project_id: ${{ secrets.G_PROJ }}
          cluster_name: 'gke-tformers-tformers-default-dev' #${{ secrets.CLUSTER_NAME }}
          cluster_region: us-central1
          release_namespace: core
          release_name: react-redux
          chart_name: ./charts/realworldchart
          helm_upgrade_args: |
            --set image.tag=${{ github.sha }}
