# This is a basic workflow to help you get started with Actions

name: testmanualapproval

# Controls when the workflow will run
#on:
#  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      runapply:
        description: 'Enter yes or no if apply should be run'
        required: true
        default: 'No'
      runinprod:
        description: 'Run on production'
        required: true
        default: 'No'
    
    #${{ github.event.inputs.runinprod =='' }}
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  log-github-event-goodies:
    name: "LOG Everything on GitHub Event"
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: |
          echo "${{toJSON(github.event)}}"
  
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: checkoutcode
        uses: actions/checkout@v2      
           
