# This is a basic workflow to help you get started with Actions

name: testmanualapproval

# Controls when the workflow will run
#on:
#  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

on:

  pull_request:
    types: [ 'labeled','opened','synchronize','reopened']
    branches: [ 'main','dev','prod' ]
    
  pull_request_review:
    types: [submitted]   #edited
    branches: ['main','dev','prod']
    paths: 
      - '**.tf'
      - '**.tfvars'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      runinprod:
        description: 'Run on production'
        required: true
        default: 'No'
    
    #${{ github.event.inputs.runinprod }}
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: checkoutcode
        uses: actions/checkout@v2      
        
      # Runs prod automatically if approved and prod label
      - name: Run prod
        if: github.event.review.state == 'approved' || contains(github.event.pull_request.labels.*.name, 'prod')  #||  ${{ github.event.label.name == 'prod' }}
        run: |
          echo "approved " ${{ github.event.label.name == 'prod' }}

      # Runs automatically on DEV
      - name: Run dev
        if: (github.event_name == 'pull_request' || github.event_name == 'push') && ${{ github.event.label.name == 'dev' }}
        run: |
          echo if decision,
          echo test, if on pull request.
          echo ${{ github.event.label.name == 'prod' }}

      # Runs a set of commands using the runners shell
      - name: Run if no ci skip
        #if: "!contains(toJSON(github.event.commits.*.message), ['skip-ci'])"
        if: "!contains(github.event.head_commit.message, 'ci skip')"
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      # Runs on prod
      - name: Run if contains prod
        #if: "!contains(toJSON(github.event.commits.*.message), ['skip-ci'])"
        if: "contains(github.event.head_commit.message, 'prod')"
        run: |
          echo Bock prod,
          echo line 2 block prod.
